---
language: python
python: "2.7"

env:
  - PLAYBOOK=test.yml

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/$PLAYBOOK -i tests/inventory --syntax-check

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
  email: false